#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api_login_check:
    path: /api/login_check

source:
  resource: "../src/Controller/"
  type:     annotation
  prefix:   /api/v1